---

- name: "Update cache"
  apt:
    update_cache: "{{ update_cache }}"
    cache_valid_time: "{{ cache_valid_time }}"

- name: "Install software"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - curl
      - wget
      - tmux
      - atop
      - ncdu
      - iotop
      - net-tools
      - git
      - xz-utils
- name: "Set timezone to your timezone"
  timezone:
    name: "{{ timezone }}"

- name: "Ensure a locale exists"
  locale_gen:
    name: "{{ my_locale }}"
    state: present

- name: "Set as default locale"
  command: "update-locale LANG={{ my_locale }} \
  LC_ALL={{ my_locale }} && dpkg-reconfigure console-setup"
